batch_size: 64
epochs: 200
eval_every_n_epochs: 1
log_every_n_steps: 1
fine_tune_from: Apr22_14-08-22_t640
learning_rate: 1e-4
weight_decay: 1e-6
model_name: resnet18

dataset:
  input_shape: (224, 224, 3)
  num_workers: 4
  valid_size: 0.2
  root_dir: "/home/zju/w4/AutoImgOrientation/data/camera/"
